//OTRA MANERA PARA IMPLENTAR UN HILO
package clases;

public class Proceso2 implements Runnable { // AGREGAMOS EL NOMBRE DE NUESTRA CLASE AL METODO Y LO IMPLEMENTAMOS LA INTERFAZ RUNNABLE

    @Override// AGREGAMOS ESTA PALABRA PARA PODER ESCRIBIRLO
    public void run() { // SE AGREGA EL METODO RUN
        for (int i = 0; i <= 5; i++) { // SE AGREGA UN CICLO FOR DICIENDO QUE I ES IGUAL A 0, MIENTRAS I SEA MENOR O IGUAL QUE 5; I SE IRA INCREMENTANDO EN UNO A UNO.
            System.out.println("Proceso 2");  // MANDAMOS UN MENSAJE PARA SABER QUE ES LO QUE VAMOS A ESTAR IMPRIMIENDO
        }
    }

}
