package clases;

public class Proceso1 extends Thread{ // SE HEREDA DE LA CLASE PADRE HILO
    
    @Override // AGREGAMOS ESTA PALABRA POR QUE ESTAMOS UTILIZANDO EL POLIMORFISMO  Y POR QUE TENEMOS QUE SOBREESCRIBIR EL METODO
    public void run(){ // SE AGREGA UN METODO RUN QUE YA VIENE IMPLENTADA EN EL LENGUJAE DE JAVA, ASI MISMO LO TENEMOS QUE HEREDAR
        for(int i = 0; i <= 5; i++){ // SE AGREGA UN CICLO FOR DICIENDO QUE I ES IGUAL A 0, MIENTRAS I SEA MENOR O IGUAL QUE 5; I SE IRA INCREMENTANDO EN UNO A UNO.
            System.out.println("Proceso 1"); // MANDAMOS UN MENSAJE PARA SABER QUE ES LO QUE VAMOS A ESTAR IMPRIMIENDO
        }
    }
}
